server:
  address: 0.0.0.0
  port: ${PORT:1111}
  servlet:
    context-path: "/"
spring:
  application:
    name: "reactive-application-computelematic"
  main:
    web-application-type: "reactive"
    allow-bean-definition-overriding: true
  profiles:
    active: "${SPRING_PROFILE_ACTIVE:dev}"
